# Expression DSL
MAX_EXPRESSION_DEPTH = 6
MAX_EXPRESSION_OPERATIONS = 20
MAX_NUMERIC_MAGNITUDE = 10**12

# Guard DSL
MAX_GUARD_PREDICATES = 20
MAX_PREDICATE_TERMS = 6

# Params DSL
MAX_PARAMS_FIELDS = 20
MAX_ARRAY_ITEMS = 12
MAX_STRING_LENGTH = 200
MAX_ENUM_CHOICES = 16

# Animation DSL
MAX_ANIMATION_NODES = 60
MAX_ANIMATION_DEPTH = 8
MAX_LABEL_TEXT_LENGTH = 80
MAX_ANIMATION_STEPS = 40
MAX_COORDINATE_MAGNITUDE = 10.0
MAX_TOTAL_DURATION_SECONDS = 30.0
